image: vioneta/{arch}-hassio-dns
shadow_repository: ghcr.io/vioneta
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.14
  armhf: ghcr.io/home-assistant/armhf-base:3.14
  armv7: ghcr.io/home-assistant/armv7-base:3.14
  amd64: ghcr.io/home-assistant/amd64-base:3.14
  i386: ghcr.io/home-assistant/i386-base:3.14
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
labels:
  io.hass.type: dns
  org.opencontainers.image.title: VionetaOS DNS Plugin
  org.opencontainers.image.description: VionetaOS Supervisor plugin for DNS
  org.opencontainers.image.source: https://github.com/Vioneta/plugin-dns
  org.opencontainers.image.authors: The VionetaOS Authors
  org.opencontainers.image.url: https://www.vioneta.io/
  org.opencontainers.image.documentation: https://www.vioneta.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  COREDNS_VERSION: 1.8.4
